In [14]:
import pandas as pd

df_user = pd.read_csv('dataset/User.csv')
df_user.head(5)

,User_id,Email,Password,Name,Gender,age,Kpopers,JapanLovers,AnimalLovers,Quite,MusicLovers,BookLovers,ArtLovers,ViewsLovers,CoffeeLovers,NonCoffeeLovers,groupsComer
0,1,cpapachristophorou0@elegantthemes.com,"uE9~"")TKtV.uYDvJ",Cam Papachristophorou,prefer not to say,41,0,1,0,1,1,1,1,0,0,1,1
1,2,sgreatbach1@cmu.edu,vA3{#>Fyt7,Sarina Greatbach,male,30,1,1,1,0,1,0,1,0,1,1,1
2,3,ssnalum2@irs.gov,hF6)Oay*M/s7j#&},Salomone Snalum,female,19,1,1,1,1,1,1,0,1,1,1,0
3,4,abrunton3@cyberchimps.com,"lF3)M""1c$w?F",Arleta Brunton,female,30,1,0,1,1,1,0,0,0,0,1,1
4,5,adukelow4@independent.co.uk,rB0}A`1b,Andonis Dukelow,female,42,0,0,1,1,0,1,0,1,0,1,0

In [24]:
df_user.columns

Index(['User_id', 'Email', 'Password', 'Name', 'Gender', 'age ', 'Kpopers',
       'JapanLovers', 'AnimalLovers', 'Quite', 'MusicLovers', 'BookLovers',
       'ArtLovers', 'ViewsLovers', 'CoffeeLovers', 'NonCoffeeLovers',
       'groupsComer'],
      dtype='object')

In [15]:
df_cafe = pd.read_csv('dataset/New_KafeJakarta.csv')
df_cafe.head(5)

,cafe_id,name,description,website,featured_image,main_category,categories,workday_timing,closed_on,phone,...,MeetingCafe,StudyCafe,Cafe with a good views,FamilyCafe,CountryFood,Smoking,NonSmoking,Coffee,NonCoffee,GardenCafe
0,ChIJLSH8Jz_0aS4R_fiIMX4JkO8,Bakoel Koffie Cikini,Tempat mengolah kopi yang menyajikan kopi klas...,http://bakoelkoffie.com/,https://lh5.googleusercontent.com/p/AF1QipOSBs...,Kedai Kopi,"Kedai Kopi, Kafe",08.00-23.30,NaN,(021) 31936608,...,1,1,0,0,0,1,1,1,1,0
1,ChIJtX1aSBT0aS4RYeoXrSXRWCY,Anomali Coffee Menteng,NaN,http://store.anomalicoffee.com/,https://lh5.googleusercontent.com/p/AF1QipNGod...,Mesin Sangrai Kopi,"Mesin Sangrai Kopi, Kafe, Kedai Kopi",07.00-23.00,NaN,(021) 3106370,...,1,1,0,0,0,1,1,1,1,0
2,ChIJ9UFwzvbzaS4R91dtdzt6_U8,Lucky Cat Coffee & Kitchen,"Kafe luas 2 lantai yang menyajikan kopi, makan...",https://www.instagram.com/luckycatcoffeekitchen/,https://lh5.googleusercontent.com/p/AF1QipNOeR...,Kedai Kopi,"Kedai Kopi, Kafe, Restoran",Buka 24 jam,NaN,(021) 52961475,...,1,1,0,1,0,1,0,1,1,1
3,ChIJUbFWB1vxaS4Rz4bnXgpxEoc,Anomali Coffee,NaN,http://store.anomalicoffee.com/,https://lh5.googleusercontent.com/p/AF1QipPVGz...,Kafe,"Kafe, Kedai Kopi",07.00-23.00,NaN,(021) 52920102,...,1,1,0,0,0,1,1,1,1,0
4,ChIJZ3frHBX0aS4Rb3PvKlxkrHk,Giyanti Coffee Roastery,Tempat nongkrong dan menikmati kopi dengan bij...,http://www.giyanticoffeeroastery.com/,https://lh3.googleusercontent.com/gps-proxy/AF...,Mesin Sangrai Kopi,"Mesin Sangrai Kopi, Kedai Kopi, Toko kopi, Res...",08.30-17.30,Senin,(021) 31923698,...,1,1,0,0,0,1,1,1,0,0

In [19]:
df_cafe.columns

Index(['cafe_id', 'name', 'description', 'website', 'featured_image',
       'main_category', 'categories', 'workday_timing', 'closed_on', 'phone',
       'address', 'review_keywords', 'link', 'outdoor', 'Indoor',
       'RetroVintage', 'MinimalisCafe', 'IndustrialCafe', 'ModernCafe',
       'ArtCafe', 'PetCafe', 'BooksCafe', '24HoursCafe', 'MeetingCafe',
       'StudyCafe', 'Cafe with a good views', 'FamilyCafe', 'CountryFood',
       'Smoking', 'NonSmoking', 'Coffee', 'NonCoffee', 'GardenCafe'],
      dtype='object')

In [ ]:
# kolom_float = df_user[['outdoor', 'Indoor', 'RetroVintage', 'MinimalisCafe', 'IndustrialCafe', 'ModernCafe', 'ArtCafe', 'PetCafe', 'BooksCafe', 
#               '24HoursCafe', 'MeetingCafe', 'StudyCafe', 'goodViews', 'FamilyCafe', 'CountryFood', 'Smoking', 'NonSmoking', 'Coffee', 
#               'NonCoffee', 'GardenCafe']]

# df_user[kolom_float] = df_user[kolom_float].fillna(0)

# # Mengubah data float menjadi int
# df_user[kolom_float] = df_user[kolom_float].astype(int)

# df_user.head(5)

In [22]:
df_cafe[['outdoor', 'Indoor', 'RetroVintage', 'MinimalisCafe', 'IndustrialCafe', 
         'ModernCafe', 'ArtCafe', 'PetCafe', 'BooksCafe', '24HoursCafe', 
         'MeetingCafe', 'StudyCafe', 'Cafe with a good views', 'FamilyCafe', 'CountryFood', 
         'Smoking', 'NonSmoking', 'Coffee', 'NonCoffee', 'GardenCafe']].astype(bool)

,outdoor,Indoor,RetroVintage,MinimalisCafe,IndustrialCafe,ModernCafe,ArtCafe,PetCafe,BooksCafe,24HoursCafe,MeetingCafe,StudyCafe,Cafe with a good views,FamilyCafe,CountryFood,Smoking,NonSmoking,Coffee,NonCoffee,GardenCafe
0,True,True,True,False,False,False,True,False,False,False,True,True,False,False,False,True,True,True,True,False
1,True,True,False,True,False,True,False,False,False,False,True,True,False,False,False,True,True,True,True,False
2,True,True,False,True,False,False,False,False,False,True,True,True,False,True,False,True,False,True,True,True
3,True,True,False,False,True,False,False,False,False,False,True,True,False,False,False,True,True,True,True,False
4,True,True,False,True,False,False,True,False,False,False,True,True,False,False,False,True,True,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,True,False,False,False,False,False,False,False,False,False,False,False,True,True,False,True,True,True,True,True
98,True,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,True,True,True,True
99,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,True,True,True,False
100,True,True,True,False,True,False,False,False,False,False,False,False,False,False,False,True,True,True,True,False
101,False,True,True,True,False,False,False,False,False,False,True,True,False,False,False,False,True,True,True,False

In [23]:
# Mengubah kolom-kolom yang berisi nilai 0 dan 1 menjadi tipe data boolean
df_user[['Kpopers', 'JapanLovers', 'AnimalLovers', 'Quite', 
        'MusicLovers', 'BookLovers', 'ArtLovers', 'ViewsLovers', 
        'CoffeeLovers', 'NonCoffeeLovers', 'groupsComer']].astype(bool)

,Kpopers,JapanLovers,AnimalLovers,Quite,MusicLovers,BookLovers,ArtLovers,ViewsLovers,CoffeeLovers,NonCoffeeLovers,groupsComer
0,False,True,False,True,True,True,True,False,False,True,True
1,True,True,True,False,True,False,True,False,True,True,True
2,True,True,True,True,True,True,False,True,True,True,False
3,True,False,True,True,True,False,False,False,False,True,True
4,False,False,True,True,False,True,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...
995,True,True,False,True,False,False,False,True,True,True,False
996,True,True,True,False,True,True,True,False,False,False,False
997,False,False,False,True,True,False,True,False,True,True,True
998,True,True,False,False,False,False,True,True,False,False,False
999,True,True,True,True,False,True,False,True,False,True,True

In [26]:
from sklearn.metrics.pairwise import cosine_similarity

# Menghitung kemiripan antara pengguna
user_similarity = cosine_similarity(df_user.drop(['Email', 'Password', 'Name', 'Gender', 'age '], axis=1))

In [27]:
import numpy as np

# Fungsi untuk merekomendasikan tipe cafe berdasarkan preferensi pengguna
def recommend_cafe(user_id, df_user, user_similarity):
    # Mengambil indeks pengguna
    user_index = df_user[df_user['User_id'] == user_id].index[0]

    # Menghitung kemiripan antara pengguna lain dan pengguna saat ini
    similarity_scores = list(enumerate(user_similarity[user_index]))

    # Mengurutkan pengguna berdasarkan kemiripan
    similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)

    # Mengambil indeks pengguna yang paling mirip
    most_similar_user_index = similarity_scores[1][0]

    # Mengambil preferensi pengguna yang paling mirip
    most_similar_user_preferences = df_user.iloc[most_similar_user_index][['Kpopers', 'JapanLovers', 'AnimalLovers', 'Quite', 
        'MusicLovers', 'BookLovers', 'ArtLovers', 'ViewsLovers', 
        'CoffeeLovers', 'NonCoffeeLovers', 'groupsComer']]

    # Mengambil preferensi pengguna saat ini
    user_preferences = df_user.iloc[user_index][['Kpopers', 'JapanLovers', 'AnimalLovers', 'Quite', 
        'MusicLovers', 'BookLovers', 'ArtLovers', 'ViewsLovers', 
        'CoffeeLovers', 'NonCoffeeLovers', 'groupsComer']]

    # Menghitung perbedaan antara preferensi pengguna saat ini dan pengguna yang paling mirip
    difference = np.subtract(most_similar_user_preferences, user_preferences)

    # Mengambil tipe cafe yang disukai oleh pengguna yang paling mirip dan tidak disukai oleh pengguna saat ini
    recommended_cafe = difference[difference > 0].index.tolist()

    # Mengembalikan tipe cafe yang direkomendasikan
    return recommended_cafe

In [28]:
# Contoh penggunaan fungsi recommend_cafe
user_id = 1
recommended_cafe = recommend_cafe(user_id, df_user, user_similarity)
print("Tipe cafe yang direkomendasikan untuk user_id", user_id, "adalah:", recommended_cafe)

TypeError: numpy boolean subtract, the `-` operator, is not supported, use the bitwise_xor, the `^` operator, or the logical_xor function instead.