In [44]:
import pandas as pd

df = pd.read_csv('dataset/Dataset_PalatePicks.csv')
df.head(10)

,User_id,Email,Password,Name,Gender,age,Kpopers,JapanLovers,AnimalLovers,Quite,...,StudyCafe,goodViews,FamilyCafe,CountryFood,Smoking,NonSmoking,Coffee,NonCoffee,GardenCafe,Rating
0,1,cpapachristophorou0@elegantthemes.com,"uE9~"")TKtV.uYDvJ",Cam Papachristophorou,prefer not to say,41,0,1,0,1,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,3.0
1,2,sgreatbach1@cmu.edu,vA3{#>Fyt7,Sarina Greatbach,male,30,1,1,1,0,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,5.0
2,3,ssnalum2@irs.gov,hF6)Oay*M/s7j#&},Salomone Snalum,female,19,1,1,1,1,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,4.0
3,4,abrunton3@cyberchimps.com,"lF3)M""1c$w?F",Arleta Brunton,female,30,1,0,1,1,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0
4,5,adukelow4@independent.co.uk,rB0}A`1b,Andonis Dukelow,female,42,0,0,1,1,...,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,5.0
5,6,mvarga5@nih.gov,qM8/8kD=2E4w>gPE,Marysa Varga,male,17,1,0,1,1,...,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,5.0
6,7,jdymock6@hubpages.com,sB5&e.Nu(k,Judah Dymock,prefer not to say,35,0,1,1,1,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,5.0
7,8,mdudman7@nsw.gov.au,xY0#NHKg5u,Miquela Dudman,male,41,0,0,1,1,...,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,3.0
8,9,rsallier8@mapy.cz,rO1&ep&jZf?D/,Raddie Sallier,male,34,1,0,0,1,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0
9,10,brickett9@mediafire.com,pX9'9o_q4CtnIdd,Birgit Rickett,male,21,0,0,0,0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,3.0

In [66]:
kolom_float = ['outdoor', 'Indoor', 'RetroVintage', 'MinimalisCafe', 'IndustrialCafe', 'ModernCafe', 'ArtCafe', 'PetCafe', 'BooksCafe', 
              '24HoursCafe', 'MeetingCafe', 'StudyCafe', 'goodViews', 'FamilyCafe', 'CountryFood', 'Smoking', 'NonSmoking', 'Coffee', 
              'NonCoffee', 'GardenCafe', 'Rating']

df[kolom_float] = df[kolom_float].fillna(0)

# Mengubah data float menjadi int
df[kolom_float] = df[kolom_float].astype(int)

df.head(5)

,User_id,Email,Password,User_Name,Gender,age,Kpopers,JapanLovers,AnimalLovers,Quite,...,StudyCafe,goodViews,FamilyCafe,CountryFood,Smoking,NonSmoking,Coffee,NonCoffee,GardenCafe,Rating
0,1,cpapachristophorou0@elegantthemes.com,"uE9~"")TKtV.uYDvJ",Cam Papachristophorou,prefer not to say,41,False,True,False,True,...,1,0,0,0,1,1,1,1,0,3
1,2,sgreatbach1@cmu.edu,vA3{#>Fyt7,Sarina Greatbach,male,30,True,True,True,False,...,1,0,0,0,1,1,1,1,0,5
2,3,ssnalum2@irs.gov,hF6)Oay*M/s7j#&},Salomone Snalum,female,19,True,True,True,True,...,1,0,1,0,1,0,1,1,1,4
3,4,abrunton3@cyberchimps.com,"lF3)M""1c$w?F",Arleta Brunton,female,30,True,False,True,True,...,1,0,0,0,1,1,1,1,0,1
4,5,adukelow4@independent.co.uk,rB0}A`1b,Andonis Dukelow,female,42,False,False,True,True,...,1,0,0,0,1,1,1,0,0,5

In [67]:
df = df.rename(columns={'Name':'User_Name', 'name':'cafe_name'})

In [68]:
df.columns

Index(['User_id', 'Email', 'Password', 'User_Name', 'Gender', 'age ',
       'Kpopers', 'JapanLovers', 'AnimalLovers', 'Quite', 'MusicLovers',
       'BookLovers', 'ArtLovers', 'ViewsLovers', 'CoffeeLovers',
       'NonCoffeeLovers', 'groupsComer', 'cafe_id', 'cafe_name', 'description',
       'website', 'featured_image', 'main_category', 'categories',
       'workday_timing', 'closed_on', 'phone', 'address', 'review_keywords',
       'link', 'outdoor', 'Indoor', 'RetroVintage', 'MinimalisCafe',
       'IndustrialCafe', 'ModernCafe', 'ArtCafe', 'PetCafe', 'BooksCafe',
       '24HoursCafe', 'MeetingCafe', 'StudyCafe', 'goodViews', 'FamilyCafe',
       'CountryFood', 'Smoking', 'NonSmoking', 'Coffee', 'NonCoffee',
       'GardenCafe', 'Rating'],
      dtype='object')

In [69]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import tensorflow as tf
from tensorflow.keras.layers import Input, Embedding, Dot, Flatten
from tensorflow.keras.models import Model

In [70]:
# Mengubah kolom-kolom yang berisi nilai 0 dan 1 menjadi tipe data boolean
df[['Kpopers', 'JapanLovers', 'AnimalLovers', 'Quite', 'MusicLovers', 'BookLovers', 'ArtLovers', 'ViewsLovers', 
    'CoffeeLovers', 'NonCoffeeLovers', 'groupsComer']] = df[['Kpopers', 'JapanLovers', 'AnimalLovers', 'Quite', 
                                                             'MusicLovers', 'BookLovers', 'ArtLovers', 'ViewsLovers', 
                                                             'CoffeeLovers', 'NonCoffeeLovers', 'groupsComer']].astype(bool)

In [71]:
# Menghitung jumlah pengguna dan tipe cafe
n_users, n_cafes = len(df['User_id'].unique()), len(df['cafe_id'].unique())

In [72]:
# Membuat model
user_input = Input(shape=[1])
cafe_input = Input(shape=[1])
user_embedding = Embedding(n_users, 10)(user_input)
cafe_embedding = Embedding(n_cafes, 10)(cafe_input)
user_vec = Flatten()(user_embedding)
cafe_vec = Flatten()(cafe_embedding)
prod = Dot(axes=1)([user_vec, cafe_vec])
model = Model([user_input, cafe_input], prod)
model.compile(optimizer='adam', loss='mean_squared_error')

In [77]:
# Membuat array rating
X = df[['User_Name', 'outdoor', 'Indoor', 'RetroVintage', 'MinimalisCafe', 'IndustrialCafe', 'ModernCafe', 
        'ArtCafe', 'PetCafe', 'BooksCafe', '24HoursCafe', 'MeetingCafe', 'StudyCafe', 'goodViews', 'FamilyCafe', 
        'CountryFood', 'Smoking', 'NonSmoking', 'Coffee', 'NonCoffee', 'GardenCafe']].values
y = df['Rating'].values

In [78]:
# Melatih model
model.fit(x=[X[:,0], X[:,1:21]], y=y, epochs=10)

ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type int).

In [ ]:
# Fungsi untuk merekomendasikan tipe cafe berdasarkan preferensi pengguna
def recommend_cafe(user_name, df, model):
    # Mengambil indeks pengguna
    user_index = df[df['Name'] == user_name].index[0]

    # Mengambil preferensi pengguna
    user_preferences = df.iloc[user_index][['outdoor', 'Indoor', 'RetroVintage', 'MinimalisCafe', 'IndustrialCafe', 'ModernCafe', 'ArtCafe', 'PetCafe', 'BooksCafe', '24HoursCafe', 'MeetingCafe', 'StudyCafe', 'goodViews', 'FamilyCafe', 'CountryFood', 'Smoking', 'NonSmoking', 'Coffee', 'NonCoffee', 'GardenCafe']].values.reshape(1,-1)

    # Menghitung rating untuk setiap tipe cafe
    ratings = model.predict([np.array([user_index]*n_cafes), np.arange(n_cafes)])

    # Mengambil tipe cafe yang disukai oleh pengguna saat ini
    user_preferences = df.iloc[user_index][['outdoor', 'Indoor', 'RetroVintage', 'MinimalisCafe', 'IndustrialCafe', 'ModernCafe', 'ArtCafe', 'PetCafe', 'BooksCafe', '24HoursCafe', 'MeetingCafe', 'StudyCafe', 'goodViews', 'FamilyCafe', 'CountryFood', 'Smoking', 'NonSmoking', 'Coffee', 'NonCoffee', 'GardenCafe']]

    # Mengambil tipe cafe yang direkomendasikan
    recommended_cafe = df.columns[1:][ratings[user_index]>ratings[user_index].mean()]

    # Mengembalikan tipe cafe yang direkomendasikan
    return recommended_cafe

In [ ]:
# Contoh penggunaan fungsi recommend_cafe
user_name = 'John'
recommended_cafe = recommend_cafe(user_name, df, model)
print("Tipe cafe yang direkomendasikan untuk", user_name, "adalah:", recommended_cafe)